name: Merge branch

on:
  workflow_dispatch:
    inputs:
      branch:
        type: string
        required: true
        description: Branch to merge

jobs:
  merge-branch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout specified branch
        uses: actions/checkout@v4
        with:
          ref: ${{github.event.inputs.branch}}

      - name: Configure git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Fetch origin/main
        run: |
          git fetch --depth 1 origin main

      - name: Merge branch and push
        run: |
          git checkout main
          git merge --squash ${{github.event.inputs.branch}}
          git commit -m ${{github.event.inputs.branch}}
          git push origin ${{github.event.inputs.branch}} --delete
          git push origin main
