name: Sync

on:
  workflow_dispatch:

env:
  CLIENT_IDS: ${{secrets.CLIENT_IDS}}
  CLIENT_SECRETS: ${{secrets.CLIENT_SECRETS}}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Install gems
      run: bundle install

    - name: Sync data
      run: ruby scripts/sync.rb

    - name: Commit and push
      run: ruby scripts/commit_and_push.rb
