name: Sync

on:
  workflow_dispatch:

env:
  CLIENT_IDS: ${{secrets.CLIENT_IDS}}
  CLIENT_SECRETS: ${{secrets.CLIENT_SECRETS}}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

    - name: Set cache key
      run: |
        echo CACHE_KEY=$(node -e 'console.log(new Date().toISOString().split("T")[0])') >> $GITHUB_ENV

    - name: Restore cache
      uses: actions/cache/restore@v4
      with:
        path: |
          .git
        key: ${{env.CACHE_KEY}}-${{github.head_ref}}-${{hashFiles('output/*.json')}}
        restore-keys: |
            ${{env.CACHE_KEY}}-${{github.head_ref}}-
            ${{env.CACHE_KEY}}-

    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Install gems
      run: bundle install

    - name: Checkout daily branch
      run: ruby scripts/checkout_branch.rb

    - name: Sync data
      run: ruby scripts/sync.rb

    - name: Commit and push
      run: ruby scripts/commit_and_push.rb

    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: |
          .git
        key: ${{env.CACHE_KEY}}-${{github.head_ref}}-${{hashFiles('output/*.json')}}
