name: Sync

on:
  workflow_dispatch:
  schedule:
    - cron:  '43 14 * * *'

env:
  CLIENT_ID: ${{secrets.CLIENT_ID}}
  CLIENT_SECRET: ${{secrets.CLIENT_SECRET}}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Install gems
      run: bundle install

    - name: Sync data
      run: ruby src/main.rb

    - name: Commit and push
      run: |-
        git config user.name "Github Actions"
        git config user.email "actions@users.noreply.github.com"
        git add output/
        timestamp=$(date -u)
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push