name: Sync

on:
  workflow_dispatch:

env:
  CLIENT_IDS: ${{secrets.CLIENT_IDS}}
  CLIENT_SECRETS: ${{secrets.CLIENT_SECRETS}}

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:

    - name: Set cache key
      run: |
        echo CURRENT_CACHE_KEY=$(node -e 'console.log(new Date().toISOString())') >> $GITHUB_ENV
        echo SHORT_CACHE_KEY=$(node -e 'console.log(new Date().toISOString().split("T")[0])') >> $GITHUB_ENV

    - name: Restore cache
      id: restore-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          .git
        key: ${{env.CURRENT_CACHE_KEY}}
        restore-keys: |
          ${{env.CURRENT_CACHE_KEY}}
          ${{env.SHORT_CACHE_KEY}}

    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
        bundler-cache: true

    - name: Install gems
      run: bundle install

    - name: Checkout daily branch
      run: ruby scripts/checkout_branch.rb --skip-pull ${{steps.restore-cache.outputs.cache-matched-key}}

    - name: Sync data
      run: ruby scripts/sync.rb

    - name: Commit and push
      run: ruby scripts/commit_and_push.rb

    - name: Save cache
      uses: actions/cache/save@v4
      with:
        path: |
          .git
        key: ${{env.CURRENT_CACHE_KEY}}
